// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WIMP_Server.Data;

namespace WIMP_Server.Migrations
{
    [DbContext(typeof(WimpDbContext))]
    partial class WimpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WIMP_Server.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WIMP_Server.Models.Intel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClear")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpike")
                        .HasColumnType("bit");

                    b.Property<int?>("ReportedById")
                        .HasColumnType("int");

                    b.Property<int?>("ShipId")
                        .HasColumnType("int");

                    b.Property<int>("StarSystemId")
                        .HasColumnType("int");

                    b.Property<int?>("StargateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ReportedById");

                    b.HasIndex("ShipId");

                    b.HasIndex("StarSystemId");

                    b.HasIndex("StargateId");

                    b.ToTable("Intel");
                });

            modelBuilder.Entity("WIMP_Server.Models.Ship", b =>
                {
                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShipId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("WIMP_Server.Models.StarSystem", b =>
                {
                    b.Property<int>("StarSystemId")
                        .HasColumnType("int");

                    b.Property<int?>("ConstellationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StarSystemId");

                    b.ToTable("StarSystems");
                });

            modelBuilder.Entity("WIMP_Server.Models.Stargate", b =>
                {
                    b.Property<int>("StargateId")
                        .HasColumnType("int");

                    b.Property<int?>("DstStarSystemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SrcStarSystemId")
                        .HasColumnType("int");

                    b.HasKey("StargateId");

                    b.HasIndex("DstStarSystemId");

                    b.HasIndex("SrcStarSystemId");

                    b.ToTable("Stargates");
                });

            modelBuilder.Entity("WIMP_Server.Models.Intel", b =>
                {
                    b.HasOne("WIMP_Server.Models.Character", "Character")
                        .WithMany("Intel")
                        .HasForeignKey("CharacterId");

                    b.HasOne("WIMP_Server.Models.Character", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedById");

                    b.HasOne("WIMP_Server.Models.Ship", "Ship")
                        .WithMany("Intel")
                        .HasForeignKey("ShipId");

                    b.HasOne("WIMP_Server.Models.StarSystem", "StarSystem")
                        .WithMany("Intel")
                        .HasForeignKey("StarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WIMP_Server.Models.Stargate", null)
                        .WithMany("Intel")
                        .HasForeignKey("StargateId");

                    b.Navigation("Character");

                    b.Navigation("ReportedBy");

                    b.Navigation("Ship");

                    b.Navigation("StarSystem");
                });

            modelBuilder.Entity("WIMP_Server.Models.Stargate", b =>
                {
                    b.HasOne("WIMP_Server.Models.StarSystem", "DstStarSystem")
                        .WithMany("IncomingStargates")
                        .HasForeignKey("DstStarSystemId");

                    b.HasOne("WIMP_Server.Models.StarSystem", "SrcStarSystem")
                        .WithMany("OutgoingStargates")
                        .HasForeignKey("SrcStarSystemId");

                    b.Navigation("DstStarSystem");

                    b.Navigation("SrcStarSystem");
                });

            modelBuilder.Entity("WIMP_Server.Models.Character", b =>
                {
                    b.Navigation("Intel");
                });

            modelBuilder.Entity("WIMP_Server.Models.Ship", b =>
                {
                    b.Navigation("Intel");
                });

            modelBuilder.Entity("WIMP_Server.Models.StarSystem", b =>
                {
                    b.Navigation("IncomingStargates");

                    b.Navigation("Intel");

                    b.Navigation("OutgoingStargates");
                });

            modelBuilder.Entity("WIMP_Server.Models.Stargate", b =>
                {
                    b.Navigation("Intel");
                });
#pragma warning restore 612, 618
        }
    }
}
